### ISSUE TITLE
Build error: variant or associated item not found in `FontTransform`

### ISSUE THREAD

**Issue by kongchenglc** [plotters-rs/plotters-wasm-demo#1]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/20537203/180964481-f349ccf0-ca2e-48f4-92d8-e5142add4776.png">

**Comment by JuliDi** [comment]
Something wrong with the git version that is linked. You can use the one from crates.io, though. In your Cargo.toml file you can change the dependencies to

```toml
[dependencies]
plotters = "0.3.2"
wasm-bindgen = "0.2.62"
wee_alloc = "0.4.5"
web-sys = { version = "0.3.39", features = ["HtmlCanvasElement"] }
plotters-canvas = "0.3.0"

```

which fixed the issue for me.

**Comment by aaraney** [comment]
I had the same issue and @JuliDi's solution worked for me too.

**Comment by Lwfrancisco** [comment]
+1 for @JuliDi 's solution.

**Comment by spookyvision** [comment]
another option is to use this open PR instead:

```toml
[dependencies.plotters-canvas]
git = "https://github.com/AE1020/plotters-canvas"
branch = "revert-rotateangle"
```
